repos:
  - repo: https://github.com/psf/black
    rev: 23.0.0 # Replace with the version you use
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241 # Replace with the version you use
    hooks:
      - id: ruff
        additional_dependencies: []
