# Configuration for IM2LaTeX project

# Data settings
data:
  data_dir: "/Users/jeremy/hmer-im2latex/data"
  train_file: "im2latex_train_filter.lst"
  validate_file: "im2latex_validate_filter.lst"
  test_file: "im2latex_test_filter.lst"
  formulas_file: "im2latex_formulas.norm.lst"
  img_dir: "img"
  batch_size: 128
  num_workers: 0
  max_seq_length: 141  # Maximum formula length (95th percentile)
  # Additional data loading parameters
  prefetch_factor: 2
  log_frequency: 1000
  eval_batch_size_multiplier: 2
  max_eval_batch_size: 128
  load_in_memory: false
  persistent_workers: true
  pin_memory: false

# Model settings
model:
  name: "resnet_lstm"  # Options: "cnn_lstm", "resnet_lstm"
  # Encoder settings
  encoder:
    # CNN encoder settings (used when model.name = "cnn_lstm")
    cnn:
      img_height: 128
      img_width: 800
      channels: 1
      conv_filters: [32, 64, 128]
      kernel_size: 3
      pool_size: 2
      padding: "same"
    # ResNet encoder settings (used when model.name = "resnet_lstm")
    resnet:
      img_height: 128
      img_width: 800
      channels: 3
      model_name: "resnet50"  # Options: "resnet18", "resnet34", "resnet50", "resnet101", "resnet152"
      freeze_backbone: true
  # Embedding and decoder settings
  embedding_dim: 2048
  decoder:
    hidden_dim: 2048
    lstm_layers: 4
    dropout: 0.1
    attention: true

# Training settings
training:
  optimizer: "adam"
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 30
  early_stopping_patience: 10
  clip_grad_norm: 5.0
  save_checkpoint_epochs: 5
  experiment_name: "img2latex_v1"
  device: "mps"  # Options: "mps", "cuda", "cpu"
  accumulation_steps: 4  # Added gradient accumulation to reduce memory pressure 

# Evaluation settings
evaluation:
  metrics: ["loss", "accuracy", "bleu", "levenshtein"]
  bleu_n: 4  # n for BLEU-n score
  bleu_batches: 10        # Number of batches to compute BLEU on during validation
  enhanced_samples: 2     # Number of samples for enhanced metrics logging

# Logging settings

inference:
  beam_size: 0        # Default beam size (0 = greedy)
  max_length: 141     # Default maximum output sequence length
  temperature: 1.0    # Softmax temperature for sampling
  top_k: 0            # Top-k sampling parameter
  top_p: 0.0          # Top-p (nucleus) sampling parameter
logging:
  level: "INFO"
  log_to_file: true
  log_file: "train.log"
  use_colors: true

# Analysis settings
analysis:
  # Error analysis settings
  error_distance_ranges: [[0, 0], [1, 1], [2, 3], [4, "inf"]]
  samples_per_bucket: 5
  min_edit_distance: 1
  max_error_samples: 50
  max_bucket_examples: 100
  top_error_patterns: 5
  
  # Image analysis settings
  image_stats_samples: 1000
  
  # Learning curve settings
  curve_smoothing: 0.0

# Preprocessing settings
preprocessing:
  pad_value: 255
  normalization_mean: [0.485, 0.456, 0.406]  # ImageNet mean values
  normalization_std: [0.229, 0.224, 0.225]   # ImageNet std values

# Visualization settings
visualization:
  figure_size: [16, 8]
  curve_figure_size: [10, 6]